# Generated by Django 5.0.6 on 2024-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='aff_speaker1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='aff_speaker2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='con_speaker1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='con_speaker2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
