# Generated by Django 5.0.6 on 2024-07-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0003_session_constructive1_session_constructive2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='aff_speaker1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='aff_speaker2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='con_speaker1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='con_speaker2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='constructive1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='constructive2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='crossfire1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='crossfire2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='final_focus1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='final_focus2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='grand_crossfire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='rebuttal1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='rebuttal2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
