# Generated by Django 5.0.6 on 2024-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0004_alter_session_aff_speaker1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
