# Generated by Django 5.1.3 on 2025-02-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0006_session_results_session_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='debate_type',
            field=models.CharField(choices=[('Public Forum', 'Public Forum'), ('Parliamentary Debate', 'Parliamentary Debate')], default='Public Forum', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='eventType',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
