# Generated by Django 5.1.3 on 2025-02-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0007_session_debate_type_session_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='debate_type',
        ),
        migrations.AlterField(
            model_name='session',
            name='eventType',
            field=models.CharField(choices=[('Public Forum', 'Public Forum'), ('Parliamentary Debate', 'Parliamentary Debate')], default='Public Forum', max_length=50),
        ),
    ]
