# Generated by Django 5.1.3 on 2025-02-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0008_remove_session_debate_type_alter_session_eventtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='eventType',
            new_name='event_type',
        ),
    ]
